# Site settings
author: Claudia Vamesu
title: Why I want to become a software developer
header-img: img/home-bg.png
email: claudia4ro@yahoo.com
copyright_name: Claudia Vamesu
description: > # this means to ignore newlines until "baseurl:"
  The beginning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  claudiahalip

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
